# Generated by Django 3.0 on 2020-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('ground_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grounds',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
