# Generated by Django 3.0 on 2020-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='ground_image',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
